# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "localhost:8008"
pid_file: /data/homeserver.pid
public_baseurl: http://localhost:8008/
listeners:
  - port: 9000
    bind_addresses: ["0.0.0.0"]
    type: manhole
  - port: 8008
    tls: false
    type: http
    resources:
      - names: [client, federation]
        compress: false

database:
  name: sqlite3
  args:
    database: /runtime/homeserver.db

log_config: "/data/synapse.log.config.yaml"
media_store_path: /data/media_store
registration_shared_secret: "Bs01N+I2aCi0rG7ok_2MMz,k*#H0TyepJLihzAoqZ4+mw9biHd"
report_stats: true
macaroon_secret_key: "jwWma=bjU+GzEt5E#z;eDO*&.38Rz@HLyVMalC,xlV^~TOOm2D"
form_secret: "M7V:&hQ^vCwmAgsDD5rMCYU*g&7enRwruizuq0PAzABb:w-S+G"
signing_key_path: "/data/synapse.signing.key"
suppress_key_server_warning: true
trusted_key_servers:
  - server_name: "matrix.org"

enable_registration: false
password_config:
  localdb_enabled: true

auto_join_rooms:
  - "#supporter:localhost:8008"

rc_message:
  per_second: 1000
  burst_count: 1000
rc_registration:
  per_second: 1000
  burst_count: 1000
rc_login:
  address:
    per_second: 1000
    burst_count: 1000
  account:
    per_second: 1000
    burst_count: 1000
  failed_attempts:
    per_second: 1000
    burst_count: 1000
rc_admin_redaction:
  per_second: 1000
  burst_count: 1000
rc_joins:
  local:
    per_second: 1000
    burst_count: 1000
  remote:
    per_second: 1000
    burst_count: 1000
rc_3pid_validation:
  per_second: 1000
  burst_count: 1000
rc_invites:
  per_room:
    per_second: 1000
    burst_count: 1000
  per_user:
    per_second: 1000
    burst_count: 1000

oidc_providers:
  - idp_id: 01HBH8G2N6ZS3AF3C95ZQT4M2T
    idp_name: "http://localhost:5173"
    skip_verification: true
    issuer: "http://nextcloud.local"
    client_id: "VgSUqiTshGQ8oWszLaTVfBo0DDfaGUC6DDhPHIWum5nQlFlEMiXnoKVBLDLeCVKp"
    client_secret: "N0ZlODQK0r5KgpQ77cVSqXfHbC6YGVzY1ig8H7fQ4qxiljEkQOIUbzRN1Fz9Ceyp"
    client_auth_method: "client_secret_post"
    scopes: ["openid", "email", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.name }}"
        display_name_template: "{{ user.name }}"
