ls:
  .js: kebab-case | pointcase
  .ts: kebab-case | pointcase
  .tsx: kebab-case | pointcase
  .dir: regex:^[a-z0-9]+([.-/][a-z0-9]*)*$ | snakecase | kebab-case
ignore:
  - lint-staged.config.js
  - node_modules
  - .*
