ls:
  .dir: regex:^[a-z0-9]+([\.\-\/](\_\_)?[a-z0-9]*(\_\_)?)*
  .js: kebab-case | pointcase
  .ts: PascalCase | camelCase
  .tsx: PascalCase | camelCase
ignore:
  - node_modules
  - .*
  - "*.config.*"
  - "**/__tests__/**"
