services:
  element:
    image: vectorim/element-web:latest
    ports:
      - "8080:80"
    volumes:
      - ./element.config.json:/app/config.json

  nextcloud.local:
    build: ./nextcloud
    ports:
      - "80:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud_db
      - OVERWRITEPROTOCOL=http
      - OVERWRITEHOST=nextcloud.local
    volumes:
      - ./nextcloud/postInstallation.sh:/docker-entrypoint-hooks.d/post-installation/postInstallation.sh
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  synapse:
    build: synapse
    environment:
      - SYNAPSE_CONFIG_PATH=/data/synapse.server.config.yaml
    ports:
      - "8008:8008"
    volumes:
      - ./synapse:/data
    depends_on:
      nextcloud.local:
        condition: service_healthy
