issuer: http://dex.local:5556/dex

storage:
  type: sqlite3
  config:
    file: /var/sqlite/dex.db

web:
  http: dex.local:5556

grpc:
  addr: dex.local:5557

telemetry:
  http: dex.local:5558

staticClients:
  - id: synapse
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirectURIs:
      - "http://synapse.local:8008/_synapse/client/oidc/callback"
    name: "Synapse"

connectors:
  - type: mockCallback
    id: mock
    name: Example

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
